-- Inserting 50 players
INSERT INTO players (name) VALUES ('Player 1');
INSERT INTO players (name) VALUES ('Player 2');
INSERT INTO players (name) VALUES ('Player 3');
INSERT INTO players (name) VALUES ('Player 4');
INSERT INTO players (name) VALUES ('Player 5');
INSERT INTO players (name) VALUES ('Player 6');
INSERT INTO players (name) VALUES ('Player 7');
INSERT INTO players (name) VALUES ('Player 8');
INSERT INTO players (name) VALUES ('Player 9');
INSERT INTO players (name) VALUES ('Player 10');
INSERT INTO players (name) VALUES ('Player 11');
INSERT INTO players (name) VALUES ('Player 12');
INSERT INTO players (name) VALUES ('Player 13');
INSERT INTO players (name) VALUES ('Player 14');
INSERT INTO players (name) VALUES ('Player 15');
INSERT INTO players (name) VALUES ('Player 16');
INSERT INTO players (name) VALUES ('Player 17');
INSERT INTO players (name) VALUES ('Player 18');
INSERT INTO players (name) VALUES ('Player 19');
INSERT INTO players (name) VALUES ('Player 20');
INSERT INTO players (name) VALUES ('Player 21');
INSERT INTO players (name) VALUES ('Player 22');
INSERT INTO players (name) VALUES ('Player 23');
INSERT INTO players (name) VALUES ('Player 24');
INSERT INTO players (name) VALUES ('Player 25');
INSERT INTO players (name) VALUES ('Player 26');
INSERT INTO players (name) VALUES ('Player 27');
INSERT INTO players (name) VALUES ('Player 28');
INSERT INTO players (name) VALUES ('Player 29');
INSERT INTO players (name) VALUES ('Player 30');
INSERT INTO players (name) VALUES ('Player 31');
INSERT INTO players (name) VALUES ('Player 32');
INSERT INTO players (name) VALUES ('Player 33');
INSERT INTO players (name) VALUES ('Player 34');
INSERT INTO players (name) VALUES ('Player 35');
INSERT INTO players (name) VALUES ('Player 36');
INSERT INTO players (name) VALUES ('Player 37');
INSERT INTO players (name) VALUES ('Player 38');
INSERT INTO players (name) VALUES ('Player 39');
INSERT INTO players (name) VALUES ('Player 40');
INSERT INTO players (name) VALUES ('Player 41');
INSERT INTO players (name) VALUES ('Player 42');
INSERT INTO players (name) VALUES ('Player 43');
INSERT INTO players (name) VALUES ('Player 44');
INSERT INTO players (name) VALUES ('Player 45');
INSERT INTO players (name) VALUES ('Player 46');
INSERT INTO players (name) VALUES ('Player 47');
INSERT INTO players (name) VALUES ('Player 48');
INSERT INTO players (name) VALUES ('Player 49');
INSERT INTO players (name) VALUES ('Player 50');

-- Inserting 100 matches
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 6, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 10, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 14, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (15, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 18, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 22, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 26, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 30, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (31, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 34, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 38, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (39, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 42, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 46, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (47, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 50, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 5, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 9, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 13, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (16, 17, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 19, 19);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 21, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (24, 25, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 27, 27);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 29, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (32, 33, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 35, 35);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 37, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (40, 41, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 43, 43);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 45, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (48, 49, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 7, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 11, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 15, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 19, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 23, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 27, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 31, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 35, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 39, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 43, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 47, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 1, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 2, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 6, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 8, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 14, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 16, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 21, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 22, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 24, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 29, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 30, 26);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 32, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 37, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 38, 34);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 40, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 45, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 46, 42);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 48, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 4, 50);

-- Inserting 100 matches
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 6, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 10, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 14, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (15, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 18, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 22, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 26, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 30, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (31, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 34, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 38, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (39, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 42, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 46, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (47, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 50, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 5, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 9, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 13, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (16, 17, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 19, 19);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 21, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (24, 25, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 27, 27);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 29, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (32, 33, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 35, 35);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 37, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (40, 41, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 43, 43);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 45, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (48, 49, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 7, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 11, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 15, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 19, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 23, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 27, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 31, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 35, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 39, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 43, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 47, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 1, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 2, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 6, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 8, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 14, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 16, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 21, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 22, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 24, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 29, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 30, 26);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 32, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 37, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 38, 34);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 40, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 45, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 46, 42);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 48, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 4, 50);

-- Inserting 100 matches
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 6, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 10, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 14, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (15, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 18, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 22, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 26, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 30, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (31, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 34, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 38, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (39, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 42, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 46, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (47, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 50, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 5, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 9, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 13, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (16, 17, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 19, 19);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 21, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (24, 25, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 27, 27);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 29, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (32, 33, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 35, 35);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 37, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (40, 41, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 43, 43);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 45, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (48, 49, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 7, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 11, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 15, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 19, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 23, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 27, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 31, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 35, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 39, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 43, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 47, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 1, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 2, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 6, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 8, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 14, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 16, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 21, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 22, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 24, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 29, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 30, 26);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 32, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 37, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 38, 34);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 40, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 45, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 46, 42);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 48, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 4, 50);

-- Inserting 100 matches
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 6, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (7, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 10, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 14, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (15, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 18, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 22, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 26, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 30, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (31, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 34, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 38, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (39, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 42, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 46, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (47, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 50, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 5, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (8, 9, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 13, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (16, 17, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 19, 19);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 21, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (24, 25, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 27, 27);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 29, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (32, 33, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 35, 35);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 37, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (40, 41, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 43, 43);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 45, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (48, 49, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (5, 7, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 11, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (13, 15, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (14, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 19, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 20, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 23, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 24, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 27, 25);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 28, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (29, 31, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (30, 32, 32);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 35, 33);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 36, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (37, 39, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (38, 40, 40);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 43, 41);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 44, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (45, 47, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (46, 48, 48);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 1, 49);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 2, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 6, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 8, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (9, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (10, 14, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (11, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (12, 16, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 21, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 22, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 23, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 24, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 29, 29);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (26, 30, 26);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (27, 31, 31);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (28, 32, 28);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (33, 37, 37);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (34, 38, 34);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (35, 39, 39);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (36, 40, 36);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (41, 45, 45);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (42, 46, 42);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (43, 47, 47);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (44, 48, 44);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (49, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (50, 4, 50);